pool:
  name: Azure Pipelines

variables:
  BuildConfiguration: 'Release'

trigger:
  branches:
    include:
      - principal

stages:
- stage: 'SonarQube_Analysis'
  condition: and(eq(variables['runSonarQube'], 'true'), succeeded())
  jobs:
 
  - job: Job_SonarQube_analysis
    displayName: 'SonarQube Analysis'
    condition: eq(variables['runSonarQube'], 'true')
    pool:
      vmImage: 'ubuntu-latest'
                
    steps:
      - checkout: self
        clean: true

      - task: gitversion/setup@3
        displayName: 'Install GitTools'
        inputs:
          versionSpec: '5.x'

      - task: gitversion/execute@3
        displayName: 'Execute Git version'
        inputs:
          useConfigFile: true
          configFilePath: 'GitVersion.yml'
          versionSpec: '5.x'
      
      - task: SonarQubePrepare@7
        displayName: 'Prepare SonarQube Analysis'
        inputs:
          SonarQube: 'SonarQube - Github'
          scannerMode: 'dotnet'
          projectKey: $(SonarQubeProjectName)
          projectName: $(SonarQubeProjectName)
          projectVersion : $(GitVersion.SemVer)
          extraProperties: |
            sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
            sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/**/coverage.opencover.xml
            sonar.log.level=INFO
            sonar.exclusions=**/bin/**/*, **/obj/**/*, **/*.yml, **/*.yaml
            sonar.dotnet.excludeTestProjects=true
            sonar.projectBaseDir=$(Agent.BuildDirectory)

      - task: UseDotNet@2
        displayName: 'Use donet'
        inputs:
          packageType: 'sdk'
          version: '9.x'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: 'restore'
          projects: 'a3innuva.Importia.SDK.sln'
          noCache: true
          verbosityRestore : 'normal'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: 'build'
          projects: 'a3innuva.Importia.SDK.sln'
          arguments: '--configuration $(BuildConfiguration) --no-restore'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
          command: 'test'
          projects: a3innuva.Importia.SDK.sln
          arguments: '--filter "FullyQualifiedName~.tests"  -c $(BuildConfiguration) --no-build --no-restore --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover'
          testRunTitle: 'Tests'
            
      - task: SonarQubeAnalyze@7
        displayName: 'SonarQube analyze'
        continueOnError: false
