name: Build and test

on:
  push:
    branches: [ principal ]
  pull_request:
    branches: [ principal ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --framework net6.0
    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal --configuration Release --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        projectKey: "es_wke_newpol_importia_sdk"
        projectName: "es_wke_newpol_importia_sdk"
        projectVersion: ${{ steps.gitversion.outputs.semVer }}
