name: Build and test

on:
  push:
    branches: [ principal]
  pull_request:
    branches: [ principal]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --framework net6.0 /p:Version=$(GitVersion.SemVer) /p:FileVersion=$(GitVersion.SemVer) /p:AssemblyVersion=$(GitVersion.MajorMinorPatch)
    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal --configuration Release 