name: Build and test

on:
  push:
    branches: [ principal]
  pull_request:
    branches: [ principal]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
    - name: Set Version
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --framework net6.0 /p:Version=$GitVersion_SemVer /p:FileVersion=$GitVersion_SemVer /p:AssemblyVersion=$GitVersion_MajorMinorPatch
    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal --configuration Release 