name: Publish nuget
on: [workflow_dispatch]
jobs:
  Publish:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/es-wolters-kluwer/index.json -Username s-wolters-kluwer -Password ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore        
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Publish packages
      run: dotnet nuget push **.nupkg --source "GPR" --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate