name: Publish nuget
on: [workflow_dispatch]
jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x   
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
    - name: Set Version
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
    - name: Restore dependencies
      run: dotnet restore        
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release /p:Version=$GitVersion_SemVer /p:FileVersion=$GitVersion_SemVer /p:AssemblyVersion=GitVersion_MajorMinorPatch
    - name: Publish packages
      run: dotnet nuget push **.nupkg --source nuget.org --api-key ${{secrets.NUGETORG_TOKEN}} --skip-duplicate